### ISSUE TITLE
Project Report

### ISSUE THREAD

**Issue by jessealaney** [jessealaney/North_America_Passerine_Diversity_Dimensionality#1]

**Comment by zechmeunier** [comment]
I love your workflow diagram! I might shamelessly borrow some design themes :)

**Comment by McLeodMJ** [comment]
Hi Jesse! Great work, you have a massive dataset that can be very difficult to modularize so creating a master script with multiple functions is a great way to streamline your work. I love your workflow, its very clear and the color coordination is excellent. If this isn't on your repository, I would love to see it there so I can reference it for myself in the future!

**Comment by jwongala** [comment]
Your workflow diagram is great and definitely motivates me to create one of my own to be more organized.

**Comment by Angelika-Kurthen** [comment]
Hi Jesse, your workflow looks really good and thorough. I also appreciated your 'failures.' So much of coding and research is trying something out and realizing that it isn't working and doing something else.

**Comment by howardre** [comment]
Love the workflow diagram design and how you're handling such a large dataset!

**Comment by Juniper41** [comment]
Very organized and clean presentation. Your workflow is very intuitive as well. Proud of you for understanding and accepting what's working and what isn't and taking another route, that's not always an easy task.

**Comment by jessealaney** [comment]
@zechmeunier Please go for it!
